version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18

  build:
    commands:
      - echo "Installing dependencies..."
      - npm install
      - echo "Zipping deployment package..."
      - zip -r ru-whatsapp.zip index.js ./db/mongo.js ./util/util.js ./util/format.js ./util/constants.js node_modules

  post_build:
    commands:
      - echo "Updating Lambda Function..."
      - aws lambda update-function-code --function-name ru-whatsapp-bot --zip-file fileb://ru-whatsapp.zip --region sa-east-1
      - aws lambda update-function-code --function-name ru-whatsapp-pol --zip-file fileb://ru-whatsapp.zip --region sa-east-1
      - echo "Finished buildspec process"

artifacts:
  files: ru-whatsapp.zip
