AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application Model template describing your function.

Parameters:
  MongoUrl:
    Type: String
    Description: MongoDB connection URL
  NumberNewsletter:
    Type: String
    Description: Newsletter number
  FunctionName:
    Type: String
    Description: Name of the Lambda function
  ChannelUrl:
    Type: String
    Description: Channel URL for WhatsApp

Resources:
  ruSender:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref FunctionName
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 60
      Handler: index.handler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      EphemeralStorage:
        Size: 512
      Environment:
        Variables:
          CHANNEL_URL: !Ref ChannelUrl
          MONGO_URL: !Ref ${MongoUrl}
          NUMBER_NEWSLETTER: !Ref ${NumberNewsletter}
      EventInvokeConfig:
        MaximumEventAgeInSeconds: 21600
        MaximumRetryAttempts: 2
      PackageType: Zip
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
              Resource: !Sub 'arn:aws:logs:sa-east-1:624755431220:log-group:/aws/lambda/${FunctionName}:*'
            - Effect: Allow
              Action:
                - logs:CreateLogStream
                - logs:PutLogEvents
              Resource: !Sub 'arn:aws:logs:sa-east-1:624755431220:log-group:/aws/lambda/${FunctionName}:*'
      RecursiveLoop: Terminate
      SnapStart:
        ApplyOn: None
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
